name: CI

on:
  push:
    branches: [ main, initialize-dependencies ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install -y gcc-16 g++-16 ninja-build python3-pip
    - name: Install Conan
      run: pip install conan
    - name: Detect Conan profile
      run: conan profile detect --force
    - name: Install Conan dependencies
      run: |
        conan install . --build=missing \
          -s build_type=Release \
          -s compiler=gcc \
          -s compiler.version=16 \
          -s compiler.cppstd=26 \
          -c tools.build:compiler_executables="{'c': 'gcc-16', 'cpp': 'g++-16'}" \
          -c tools.cmake.cmaketoolchain:generator=Ninja
    - name: Configure
      run: cmake --preset=conan-release
    - name: Build
      run: cmake --build --preset=conan-release
